name: gasket_assembly
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.18
  - pip=23.3
  - cython
  - matplotlib-inline=0.1.6
  - numpy
  - setuptools=68.0.0
  - pip:
      - autolab-core==1.1.1
      - cowsay==6.1
      - matplotlib==3.8.1
      - opencv-python==4.9.0.80
      - packaging==23.2
      - pandas==2.1.3
      - pyopengl==3.1.7
      # - pyzed==4.0
      - requests==2.31.0
      - resources==0.0.1
      - scikit-image==0.22.0
      - scikit-learn==1.3.2
      - scipy==1.11.3
      # - ur-rtde==1.4.2
      # - ur5py==0.1.0
